language: rust
os:
  - linux
  - windows
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true
script:
  - rustc --version 
  - cargo --version
  - cargo build --all-features --verbose
  - cargo test --verbose
