[package]
edition = "2018"
name = "alog"
version = "0.5.7"
authors = ["thyrc <thyrc@users.noreply.github.com>"]
description = "Anonymize 'Combined Log Format' data"
license = "MIT"
repository = "https://github.com/thyrc/alog"
documentation="https://docs.rs/alog/"
readme = "README.md"
keywords = ["log", "anonymize", "parse"]
categories = ["parsing", "command-line-utilities"]
exclude = [
    "snippets",
    ".github"
]

[badges]
travis-ci = { repository = "thyrc/alog" }

[profile.release]
panic = 'abort'
lto = true
debug = true

[dependencies]
clap = { version = "2.33.0", optional = true }

[lib]
name = "alog"
path = "src/lib.rs"

[features]
alog-cli = [ "clap" ]

[[bin]]
name = "alog"
required-features = [ "alog-cli" ]
