[package]
edition = "2018"
name = "alog"
version = "0.2.3"
authors = ["thyrc <thyrc@users.noreply.github.com>"]
description = "Anonymize 'Combined Log Format' data"
license = "MIT"
repository = "https://github.com/thyrc/alog.git"
keywords = ["log", "anonymize", "parse"]
categories = ["parsing", "command-line-utilities"]
exclude = [
    "snippets",
    ".github"
]

[profile.release]
panic = 'abort'
lto = true
debug = 1

[dependencies]
clap = "2.33.0"
