[package]
name = "alog"
version = "0.2.2"
authors = ["thyrc <thyrc@users.noreply.github.com>"]
edition = "2018"
publish = false
description = "Anonymize 'Combined Log Format' data"
license = "MIT"

[profile.release]
panic = 'abort'
opt-level = 'z'
lto = true
# debug = 1

[dependencies]
clap = "2"
