name: Rust

on: [push]

jobs:
  ubtuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Versions
      run: rustc --version && cargo --version
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --verbose

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Versions
      run: rustc --version && cargo --version
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --verbose
