name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v1
    - name: Versions
      run: rustc --version && cargo --version
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --verbose
